
name: build and run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print github workspace
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "github.workspace = ${{ github.workspace }}"
        echo "pr.ref = ${{github.event.pull_request.head.ref}}"
        echo "github.ref = ${{ github.ref }}"
        echo "$GITHUB_CONTEXT"
        ls -la
    # install dependencies
    - name: Boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-all-dev
    # build project
    - name: CMake
      working-directory: ${{ github.workspace }}/build
      run: cmake ..
    - name: Make
      working-directory: ${{ github.workspace }}/build
      run: make
    # run tests
    - name: Tests
      working-directory: ${{ github.workspace }}/build
      run: ./tests/do_tests
