
name: build and run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: Boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-all-dev
    - name: Gtest
      run: sudo git clone git@github.com:google/googletest.git libs/
    # build project
    - name: cmake make
      run: cmake --build build/ --target all
    # run tests
    - name: run tests
      run: build/test/do_tests
